### PR TITLE
Add an option to use thing-at-point (Fixes #8)

### LINKED ISSUE #8: Support for partial completion?
Hi!
Is it possible or planned to support partial completion in `M-x consult-yasnippet`?

I'd like to enter part of a snippet key "`tod`" and have `M-x consult-yasnippet` show me alternatives for snippets that start with "tod" (pre-filling the minibuffer with what I've already typed).

Thanks!

### PR DESCRIPTION
**Pull request by furkanusta**

### CODE REVIEW

**Comment by furkanusta** [comment]
After the initial commit I've realized that only adding the `:initial` key to `consult--read` is not enough since expansion does not remove the thing at point. That is why I had to modify `consult-yasnippet` as well. I could make things shorter by removing variables that are only used once (`thing-start` `thing-end`)

**Comment by mohkale** [comment]
Hi, thanks for working on this.

I've made a few stylistic changes, but otherwise looks good to me. However it doesn't seem to be working. If I have a buffer like this:

```elisp
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with SPC f f and enter text in its buffer.

defun
```

with my point at the end of `defun`, it does use it as initial-input on my call to consult-yasnippet but the result isn't what I expected.

```elisp
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with SPC f f and enter text in its buffer.

defun(defun fun (args)
       "docstring"
       (interactive "P")
       )
```

Also I'm not a big fan of the thing at point sticking around while you're selecting snippets. It'd be nice if it was removed while processing and if you cancel the completion session then it was placed back in (you should be able to customize the preview function to accomplish this.

**Comment by furkanusta** [comment]
I've fixed the bug where the prefix is not removed (I hope). The reason was that I was only deleting the matching parts of the thing-at-point and template-key but the list of candidates check against the name and does not require the match to beg at the beginning.

I've also added the code to remove the prefix during previews. 
I don't think it is much of a problem but if a region is selected and thing-at-point also matches it does not overwrite the whole region but still only the matching part.

**Comment by mohkale** [comment]
@furkanusta 

Sadly this also doesn't seem to be working as expected.

Screenshot_20220605_092617

Screenshot_20220605_092626

**Comment by furkanusta** [comment]
If you mean the region being active during the preview, I've added a fix. 

Your initial implementation also overwrote the selected region when expanding the template. 
I've also added that behavior as well.

**Comment by mohkale** [comment]
@furkanusta 

> If you mean the region being active during the preview, I've added a fix.

I was actually referring to the snippet expansion being corrupted. I inserted defun and if you notice the snippet was expanded correctly in the first screenshot when defun was auto-inserted into the completion interface, but when I changed the candidate the `(defun ` prefix was still there when it should've been removed. Your latest commit has fixed this issue so thanks.

Furthermore it all seems to be working (and is actually quite nice, I might try this out as well (perhaps even enable it by default at some point :smile:)). However I did encounter an error when first run.

```text
consult--read: No preview, the :state function protocol changed: (user-error "No mark set in this buffer")
```

I encountered this when loading your version of consult-yasnippet, going to the scratch buffer, inserting defun and then running `consult-yasnippet`. It's likely one of the helper functions calling a mark function when the mark has not yet been set. Please fix :-).

**Comment by furkanusta** [comment]
I am glad you liked it.

But unfortunately I wasn't able to reproduce that error. However, instead of using `(set-mark-command -1)` I am now using `(deactivate-mark)` hope this fixes the problem.

**Comment by mohkale** [comment]
Hi, sorry for the late update, I caught covid among other things :cry:.

Good news is I'm no longer getting any error from the latest commit you've pushed. Only question left is how the plugin should deal with a thing-at-point that isn't a valid snippet prefix. To me it seems to be leaving it as is in the buffer before the snippet expansion. Personally I think if you're using thing-at-point you should always be using it, not optionally leaving it behind if it doesn't match a snippet.

**Comment by furkanusta** [comment]
Oh, I hope you are better now.

You mean, if I type `deff`, execute `consult-yasnippet`, delete the extra f and select `defun`, it expands defun but leaves `deff` intact. I can remove the thing-at-point unconditionally or introduce an another customization variable (something like `consult-yasnippet-always-overwrite-thing-at-point`). Though, I prefer the former.

**Comment by mohkale** [comment]
I think an option would be best since our preferences differ ;-).

**Comment by furkanusta** [comment]
I've finally got some time to add the customization variable. 
Tested couple of cases and did not encounter any problems.
Hope it works for you as well

**Comment by mohkale** [comment]
@furkanusta 

Glad to say everythings working as I'd expect. Thanks for contributing this. I've gone ahead and cleaned up a some docstrings and linter complaints. But otherwise everything LGTM so I'm gonna go ahead and merge :-).

**Comment by memestreak** [comment]
Thank you for this @furkanusta!

**Pull request merged**
